### PR TITLE
PEP8 Compliance

### PR DESCRIPTION
**Pull request by JasonBristol**
PEP8 Compliance in most areas

### CODE REVIEW

**Comment by suresttexas00** [comment]
Totally agree... fair warning though.. The Benbot and I already butted heads on this before... He views PEP-8 as simply an "internal standard" for python module developers:

**Comment by suresttexas00** [comment]
This will make errors stand out much better.

**Comment by JasonBristol** [comment]
Yah, to some level it can be a bit much, but things like the following need to be addressed:

```python
if not cond == False:
```

This is just an overly verbose and confusing way to say:

```python
if cond:
```

**Comment by suresttexas00** [comment]
This code also needs to start using "is" and "is not" when comparing booleans and None things.

No:
`if cond == False:`

Yes:
`if cond is False:`

**Comment by JasonBristol** [comment]
Correct, particularly with membership:

if cond in conditions:
if cond not in conditions:

if object is None:
if object is not None:

For your example it can be even simpler

if cond:
if not cond:

**Pull request merged**
